#!/bin/bash
# Author: Médéric Durand
# Date: Septembre 16th 2024
# This script recursively hard deletes empty .WAV files generated by faulty audiomoths recordings
# Please refrain from using on non-local data
# Just swap the path

# Set the directory path
directory_path="C:/Projects/AudiomothData/Audiomoths_2024_empty_test"


# Find and delete empty .WAV files
find "$directory_path" -type f -name "*.WAV" -size 0 -print -delete

echo "Done"